name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Setup Emscripten
      run: |
        git submodule update --init
        cd emsdk
        ./emsdk install 3.1.3
        ./emsdk activate 3.1.3

    - name: Configure
      run: |
        cmake -S. -Bbuild-py -Dlanguage=python
        cmake -S. -Bbuild-wasm -Dlanguage=wasm -DCMAKE_TOOLCHAIN_FILE=emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake

    - name: Build
      run: |
        cmake --build build-py -j4
        cmake --build build-wasm -j4

    - name: Run artifacts
      run: |
        python python/main.py
        node wasm/main.js
