name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-2019
    env:
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Setup Emscripten
      run: |
        git submodule update --init
        cd emsdk
        emsdk.bat install 3.1.3
        emsdk.bat activate 3.1.3

    - name: Download python dependencies
      run: |
        python -m pip install ninja

    - name: Configure
      shell: cmd
      run: |
        call "%VCVARS%"
        cmake -S. -Bbuild-py -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -G Ninja
        cmake -S. -Bbuild-wasm -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -G Ninja -DCMAKE_TOOLCHAIN_FILE=emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake

    - name: Build
      shell: cmd
      run: |
        call "%VCVARS%"
        cmake --build build-py -j4
        cmake --build build-wasm -j4

    - name: Run artifacts
      run: |
        python python\main.py
        node wasm\main.js
